# TypeProf 0.21.9

# Classes
module Kagaribi
  class Collection
    MAX_RETRY_COUNT: Integer

    @firestore: Google::Cloud::Firestore

    attr_reader collection_name: String
    attr_reader database_id: String
    attr_reader logger: Logger

    def initialize: (String collection_name, ?database_id: string?, ?logger: Logger?) -> void
    def set: (String doc_key, Hash[untyped, untyped] data) -> void
    def get: (String doc_key) -> Hash[Symbol, untyped]
    def self.sanitize_key: (String key) -> String

    private

    def firestore: -> Google::Cloud::Firestore
    def sanitized_collection_name: -> String
    def sanitize_key: (String key) -> String
    def full_doc_key: (String doc_key) -> String
    def with_retry: (String label)  { -> untyped } -> untyped
    def retryable_error?: (StandardError error) -> bool
  end
end
